using System.Buffers.Binary;using System.IO;using System.Text;
namespace XR18BarControl.XR18;
public static class OscCodec
{
 public static byte[] Encode(OscMessage m){using var s=new MemoryStream();WriteString(s,m.Address);if(m.Value is object[] values){WriteString(s,","+string.Concat(values.Select(TypeTag)));foreach(var value in values)WriteValue(s,value);return s.ToArray();}switch(m.Value){case null:WriteString(s,",");break;case int i:WriteString(s,",i");WriteInt(s,i);break;case float f:WriteString(s,",f");WriteInt(s,BitConverter.SingleToInt32Bits(f));break;case string x:WriteString(s,",s");WriteString(s,x);break;default:throw new NotSupportedException("Tipo OSC no permitido");}return s.ToArray();}
 public static OscMessage Decode(ReadOnlySpan<byte>d){var o=0;var a=ReadString(d,ref o);var t=ReadString(d,ref o);object?v=t.Length<2?null:t[1]switch{'i'=>ReadInt(d,ref o),'f'=>BitConverter.Int32BitsToSingle(ReadInt(d,ref o)),'s'=>ReadString(d,ref o),_=>null};return new(a,v);}
 public static IReadOnlyList<string> DecodeStringArguments(ReadOnlySpan<byte>d){var o=0;ReadString(d,ref o);var tags=ReadString(d,ref o);var values=new List<string>();foreach(var tag in tags.Skip(1)){switch(tag){case 's':values.Add(ReadString(d,ref o));break;case 'i':case 'f':ReadInt(d,ref o);break;default:throw new FormatException($"Tipo OSC no compatible en /xinfo: {tag}");}}return values;}
 static void WriteString(Stream s,string x){var b=Encoding.UTF8.GetBytes(x);s.Write(b);s.WriteByte(0);while(s.Position%4!=0)s.WriteByte(0);}static void WriteInt(Stream s,int v){Span<byte>b=stackalloc byte[4];BinaryPrimitives.WriteInt32BigEndian(b,v);s.Write(b);}static string ReadString(ReadOnlySpan<byte>d,ref int o){var e=d[o..].IndexOf((byte)0);if(e<0)throw new FormatException("Cadena OSC inválida");var s=Encoding.UTF8.GetString(d.Slice(o,e));o=(o+e+4)&~3;return s;}static int ReadInt(ReadOnlySpan<byte>d,ref int o){if(o+4>d.Length)throw new FormatException("OSC truncado");var v=BinaryPrimitives.ReadInt32BigEndian(d.Slice(o,4));o+=4;return v;}
 static char TypeTag(object value)=>value switch{int=>'i',float=>'f',string=>'s',_=>throw new NotSupportedException("Tipo OSC no permitido")};static void WriteValue(Stream s,object value){switch(value){case int i:WriteInt(s,i);break;case float f:WriteInt(s,BitConverter.SingleToInt32Bits(f));break;case string x:WriteString(s,x);break;}}
}
