using System.Net;using System.Net.Sockets;using XR18BarControl.Audio;using XR18BarControl.Services;
namespace XR18BarControl.XR18;
public enum ConnectionState{Disconnected,Connecting,Connected}
public sealed class XR18OscClient:IDisposable
{
 readonly SemaphoreSlim _sendLock=new(1,1);UdpClient?_udp;IPEndPoint _endpoint;DateTime _lastReply;CancellationTokenSource?_runCts;int _reconfigureRequested;
 public event Action<ConnectionState>?ConnectionChanged;public event Action<OscMessage>?StateReceived;public ConnectionState State{get;private set;}=ConnectionState.Disconnected;
 public XR18OscClient(string ip,int port){_endpoint=new(IPAddress.Parse(ip),port);}public void Reconfigure(string ip,int port){_endpoint=new(IPAddress.Parse(ip),port);Interlocked.Exchange(ref _reconfigureRequested,1);AppLog.Info($"Reconfiguración de XR18 solicitada | ip={ip} puerto={port}");_udp?.Dispose();}
 public async Task RunAsync(CancellationToken applicationToken){_runCts?.Cancel();_runCts=CancellationTokenSource.CreateLinkedTokenSource(applicationToken);var ct=_runCts.Token;while(!ct.IsCancellationRequested){try{await RunSessionAsync(ct);}catch(OperationCanceledException)when(ct.IsCancellationRequested){break;}catch(Exception)when(Interlocked.Exchange(ref _reconfigureRequested,0)==1){AppLog.Info("Conexión XR18 reiniciada por cambio de configuración");}catch(Exception ex){AppLog.Error("Error de red XR18",ex);}SetState(ConnectionState.Disconnected);try{await Task.Delay(2000,ct);}catch(OperationCanceledException){break;}}}
 async Task RunSessionAsync(CancellationToken ct){SetState(ConnectionState.Connecting);_udp?.Dispose();_udp=new UdpClient(0);_udp.Connect(_endpoint);_lastReply=DateTime.UtcNow;await SendProtocolAsync(new("/xinfo"),ct);await SendProtocolAsync(new("/xremote"),ct);using var session=CancellationTokenSource.CreateLinkedTokenSource(ct);var receive=ReceiveLoopAsync(session.Token);var keepalive=KeepAliveLoopAsync(session.Token);await Task.WhenAny(receive,keepalive);session.Cancel();await Task.WhenAll(IgnoreCancellation(receive),IgnoreCancellation(keepalive));}
 async Task ReceiveLoopAsync(CancellationToken ct){while(!ct.IsCancellationRequested){var result=await _udp!.ReceiveAsync(ct);_lastReply=DateTime.UtcNow;try{var msg=OscCodec.Decode(result.Buffer);if(msg.Address is "/xinfo" or "/info" or "/status"){if(State!=ConnectionState.Connected){SetState(ConnectionState.Connected);AppLog.Info("XR18 conectado");await QueryAllAsync(ct);}}else if(XR18Commands.StatePaths.Contains(msg.Address)){AppLog.Audit($"Estado recibido de XR18 | ruta={msg.Address} valor={msg.Value}");StateReceived?.Invoke(msg);}}catch(Exception ex){AppLog.Error("Mensaje OSC inválido",ex);}}}
 async Task KeepAliveLoopAsync(CancellationToken ct){while(!ct.IsCancellationRequested){await Task.Delay(5000,ct);await SendProtocolAsync(new("/xremote"),ct);await SendProtocolAsync(new("/xinfo"),ct);if(DateTime.UtcNow-_lastReply>TimeSpan.FromSeconds(12))throw new TimeoutException("XR18 no responde");}}
 public async Task QueryAllAsync(CancellationToken ct){foreach(var p in XR18Commands.StatePaths)await SendProtocolAsync(new(p),ct);}
 public async Task SetZoneEnabledAsync(OutputMapping output,bool enabled,CancellationToken ct){EnsureConnected();foreach(var p in output.OnPaths){EnsureWhitelisted(p);await SendProtocolAsync(new(p,enabled?1:0),ct);}}
 public async Task SetZoneVolumeAsync(OutputMapping output,double percent,CancellationToken ct){EnsureConnected();percent=Math.Clamp(percent,0,100);var db=VolumeMapper.PercentToDb(percent);var value=VolumeMapper.DbToOsc(db);foreach(var p in output.FaderPaths){EnsureWhitelisted(p);await SendProtocolAsync(new(p,value),ct);}if(percent<=0)await SetZoneEnabledAsync(output,false,ct);}
 async Task SendProtocolAsync(OscMessage m,CancellationToken ct){var d=OscCodec.Encode(m);await _sendLock.WaitAsync(ct);try{await _udp!.SendAsync(d,ct);}finally{_sendLock.Release();}}
 static void EnsureWhitelisted(string p){if(!XR18Commands.StatePaths.Contains(p))throw new InvalidOperationException("Comando OSC no permitido");}void EnsureConnected(){if(State!=ConnectionState.Connected)throw new InvalidOperationException("XR18 desconectado");}void SetState(ConnectionState v){if(State==v)return;State=v;ConnectionChanged?.Invoke(v);if(v==ConnectionState.Disconnected)AppLog.Info("XR18 desconectado; se reintentará");}static async Task IgnoreCancellation(Task t){try{await t;}catch(OperationCanceledException){}}
 public void Dispose(){_runCts?.Cancel();_udp?.Dispose();_runCts?.Dispose();_sendLock.Dispose();}
}
